version: '2'

volumes:
  nginx-log-files:
  fluentbit-log-files:
  es-data:
  # fluentd-log-files:

services:
  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - nginx-log-files:/var/log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # fluent-agent:
  #   image: fluent/fluentd:v1.0-debian
  #   volumes:
  #     - nginx-log-files:/var/log
  #     - fluentd-log-files:/fluentd/log
  #     - ./fluent-agent/conf:/fluentd/etc
  #   links:
  #     - fluentd
  #   depends_on:
  #     - fluentd

  fluent-bit:
    image: fluent/fluent-bit:0.12
    volumes:
      - nginx-log-files:/var/log
      - fluentbit-log-files:/fluent-bit/log
      - ./fluent-bit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    links:
      - fluentd
    depends_on:
      - fluentd

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
