version: '2'

volumes:
  nginx-log-files:
  fluentd-log-files:

services:
  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - nginx-log-files:/var/log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  fluent-agent:
    image: fluent/fluentd:v1.0-debian
    volumes:
      - nginx-log-files:/var/log
      - fluentd-log-files:/fluentd/log
      - ./fluent-agent/conf:/fluentd/etc
    links:
      - fluentd

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"